### ISSUE TITLE
Tablet UI

### ISSUE THREAD

**Issue by asolove** [WardCunningham/Smallest-Federated-Wiki#335]
I am working on a tablet-focused UI for wiki in [a branch in my repo](https://github.com/asolove/Smallest-Federated-Wiki/tree/mobile). Please *do not* pull the current state of this code into any master branch. It is a quick prototype that breaks the desktop version. 

I'm experimenting with how the UI should work on a tablet. The central idea is to enable an uncluttered environment for exploring and reading, only showing menus and options when the user explicitly wants to engage in editing/refactoring.

- The fundamental paradigm of the columns is still in place, but it now works with touch gestures and supports inertial scrolling on iOS so it feels like a native app.
- The site icon, story history, etc. have all been moved into a floating header (see screenshot below) that hides away when the user is reading, and is only displayed when they want to edit.
- The paragraph editing commands, which used to use hover stats and double-clicks, are now in a context menu that appears after double-tapping a paragraph.

Here's what it looks like at present:

![IMG_0008_1024](https://f.cloud.github.com/assets/8495/38748/9862eec0-54fe-11e2-8f84-4d92d1ee3313.jpg)

Comments appreciated!

**Comment by thoka** [comment]
Is there some collection of problems facing using fedwiki on a tablet ?

One, that I think of, is the problem of missing modifiers for actions.
Since tablets are multi touch devices, this could be "simulated" by having a floating modifier palette on top of fedwiki, which allows to alter the action of the other finger.

**Comment by WardCunningham** [comment]
Prevailing wisdom is that designs should consider touch first, then find an equivalent way to perform operations on the desktop. The design space for federated wiki is open because wiki has chosen to use keystrokes for most special features. Tap behavior has no competition.

We have worked with several designers who have been flummoxed by the open-ended goals of federated wiki. My summary: the designers were prepared to produce a performance while federated wiki is a platform for other peoples performances. Designer's head explodes.

If you can get past the head exploding and just do something simple like make page scrolling work with reasonable ballistics then you are ready to contribute to tablet federated wiki.
